### ISSUE TITLE
Error in the fastest script

### ISSUE THREAD

**Issue by korzystka** [multiduplikator/mikrotik_blocklist#1]
Hi, great work!
But there is an issue in the "fastest" script; lack of /ip firewall address-list line:

/tool fetch url="https://raw.githubusercontent.com/multiduplikator/mikrotik_blocklist/main/blocklist_ga.rsc" mode=https

--> # enter the address-list section
--> /ip firewall address-list

:local prdkeys [find list=prod_blocklist]
[...]

**Comment by multiduplikator** [comment]
It is important that the address-list is already existing in the firewall section. You can create one with a bogus entry to start with.
If you follow the advanced firewall guide, you should have the list already created before using this script.

Here are my current two scripts:

This is the one for the download (Policy, ftp, read, write, test)
```
:log info "blocklist-DL started"
/tool fetch url="https://raw.githubusercontent.com/multiduplikator/mikrotik_blocklist/main/blocklist_ga_l.rsc" mode=https
:log info "blocklist-DL finished"
```


This is the one doing the replace/update (Policy, read, write, test)

```
:log info "blocklist-REP started"
:log info "blocklist-REP started - disabling info"
/system logging disable 0

/import file-name=blocklist_ga_l.rsc

/ip firewall address-list

:local prdkeys [find list=prod_blocklist]
:global newips

:if ([:len $newips] > 0 ) do={
	:foreach value in=$prdkeys do={
		:local keyindex [:find $newips [get $value address]]
		:if ($keyindex > 0) do={
			:set ($newips->($keyindex)) ""
		} else={
			remove $value
		}
	}
	:foreach value in=$newips do={
		:if ($value != "") do={
			add list=prod_blocklist address="$value"
		}
	}
}

:set newips

/system logging enable 0
:log info "blocklist-REP finished - enabled info"
:log info "blocklist-REP finished"
```
