### ISSUE TITLE
https://www.spamhaus.org/drop/edrop.txt merged into https://www.spamhaus.org/drop/drop.txt

### ISSUE THREAD

**Issue by TomHGitHub** [multiduplikator/mikrotik_blocklist#10]
curl https://www.spamhaus.org/drop/edrop.txt
; This list has been merged into https://www.spamhaus.org/drop/drop.txt
; Spamhaus EDROP List 2024/08/13 - (c) 2024 The Spamhaus Project SLU
; https://www.spamhaus.org/drop/edrop.txt
; Last-Modified: Tue, 13 Aug 2024 11:43:35 GMT
; Expires: Wed, 14 Aug 2024 11:43:35 GMT
; EOF

**Comment by multiduplikator** [comment]
Thanks for spotting this. Updated.
