### ISSUE TITLE
Small fix for "BY FAR THE FASTEST"

### ISSUE THREAD

**Issue by njumaen** [multiduplikator/mikrotik_blocklist#3]
Hi,

fell in love with your "BY FAR THE FASTEST" script, BUT:

There's this bug:

:local prdkeys [find list=prod_blocklist]

will fail anywhere but in _/ip firewall address-list_ !
This prevents running the script by a scheduled command.

Solution: put 

:local prdkeys... 

in the line behind

/ip firewall...

Cheers,

Ralf.

P.S. Thanks for the _test_ lists, they work but I now prefer your script.

**Comment by multiduplikator** [comment]
I think my current productive scripts have that fix already:

I am using two scripts to manage, to minimize the policy ftp usage as the second script runs for considerable time and I don't want ftp policy to be active for nothing:

**1 - Download** (Policy ftp, read, write, test)
```
:log info "blocklist-DL started"
/tool fetch url="https://raw.githubusercontent.com/multiduplikator/mikrotik_blocklist/main/blocklist_ga_l.rsc" mode=https
:log info "blocklist-DL finished"
```

**2 - Update** (Policy read, write, test)
```
:log info "blocklist-REP started"
:log info "blocklist-REP started - disabling info"
/system logging disable 0

/import file-name=blocklist_ga_l.rsc

/ip firewall address-list

:local prdkeys [find list=prod_blocklist]
:global newips

:if ([:len $newips] > 0 ) do={
	:foreach value in=$prdkeys do={
		:local keyindex [:find $newips [get $value address]]
		:if ($keyindex > 0) do={
			:set ($newips->($keyindex)) ""
		} else={
			remove $value
		}
	}
	:foreach value in=$newips do={
		:if ($value != "") do={
			add list=prod_blocklist address="$value"
		}
	}
}

:set newips

/system logging enable 0
:log info "blocklist-REP finished - enabled info"
:log info "blocklist-REP finished"
```

**Comment by multiduplikator** [comment]
Thanks for the spotting the bug in the README. Corrected. Added sample scripts.

I will take down the test lists then...

**Comment by njumaen** [comment]
Perfect!
