### ISSUE TITLE
Mikrotik HEX S stalls on the blocklist_ga _l and blocklist_ga_xl, breaks at  /import file-name=blocklist_ga_l.rsc

### ISSUE THREAD

**Issue by TomHGitHub** [multiduplikator/mikrotik_blocklist#9]
My Mikrotik HEX S stalls on the blocklist_ga _l and blocklist_ga_xl. I am pretty new to RouterOS. I added some debugging lines to the script. It breaks after logging :log info "blocklist-import started" - before /import file-name=blocklist_ga_l.rsc. blocklist_ga.rsc works without issues. System info added below the script. Thank you very for your support much in advance.

:log info "blocklist_ga_l.rsc-DL started"
/tool fetch url="https://raw.githubusercontent.com/multiduplikator/mikrotik_blocklist/main/blocklist_ga_l.rsc" mode=https
:log info "blocklist_ga_l.rsc-DL finished"

:delay 4000ms;

:log info "blocklist-REP: started"
#/system logging disable 0

:local duration [/system clock get time]
:log info "blocklist-import started"
/import file-name=blocklist_ga_l.rsc
:log info "blocklist-imported"
/ip firewall address-list

:local prdkeys [find list=prod_blocklist]
:global newips

:local countnew 0
:local countremoved 0
:local counttotal [:len $newips]
:local counterror 0

:if ($counttotal > 0 ) do={
	:log info "counttotal > 0"
	:foreach value in=$prdkeys do={
		:local keyindex [:find $newips [get $value address]]
		:if ($keyindex > 0) do={
			:set ($newips->($keyindex)) ""
		} else={
			remove $value
			:set countremoved ($countremoved+1)
		}
	}
	:foreach value in=$newips do={
		:if ($value != "") do={
			:do { add list=prod_blocklist address="$value" } on-error { :set counterror ($counterror+1) }
			:set countnew ($countnew+1)
		}
	}
}

:set newips
:set duration ([/system clock get time] - $duration)

/system logging enable 0
:log info "blocklist-REP: finished - enabled info"
:log info "blocklist-REP: finished - $countremoved removed, $countnew new, $counterror errors, in $duration / $counttotal  total"

Free Memory		152.4 MiB
Total Memory		256.0 MiB
CPU		MIPS 1004Kc V2.15
CPU Count		4
CPU Frequency		880 MHz
CPU Load		38 %
Free HDD Space		2472 KiB
Total HDD Size		16.0 MiB
Sector Writes Since Reboot		6 035
Total Sector Writes		19 019
Architecture Name		mmips
Board Name		hEX S
Version		7.15.3 (stable)
Build Time		2024-07-24 10:39:01
Factory Software		6.46.4

**Comment by multiduplikator** [comment]
Hey, sorry for the long wait.

To replicate my setup, try separating the download and the update, please. This is also to minimize policy elevation while running scripts. Esp. the second script (update) can run a loooong time.

Actually, the import can take quite some time on your hardware, and it might appear that nothing happens. I would not be surprised if it takes 5-10min, and then the same or even longer for actual update of the list. If you add CPU and Memory to Dashboard in winbox, you can see if the machine is under load or not. Did you try that?

Also, did you try the smallest version?


Here are the two scripts copied verbatim from my router, one for download, 1 for update.

Download (policy: ftp, read, write, test):
```
:log info "blocklist-DL started"
/tool fetch url="https://raw.githubusercontent.com/multiduplikator/mikrotik_blocklist/main/blocklist_ga_l.rsc" mode=https
:log info "blocklist-DL finished"
```

Update (policy: read, write, test)
```
:log info "blocklist-REP: started"
:log info "blocklist-REP: started - disabling info"
/system logging disable 0

:local duration [/system clock get time]

/import file-name=blocklist_ga_l.rsc

/ip firewall address-list

:local prdkeys [find list=prod_blocklist]
:global newips

:local countnew 0
:local countremoved 0
:local counttotal [:len $newips]

:if ($counttotal > 0 ) do={
	:foreach value in=$prdkeys do={
		:local keyindex [:find $newips [get $value address]]
		:if ($keyindex > 0) do={
			:set ($newips->($keyindex)) ""
		} else={
			remove $value
			:set countremoved ($countremoved+1)
		}
	}
	:foreach value in=$newips do={
		:if ($value != "") do={
			add list=prod_blocklist address="$value"
			:set countnew ($countnew+1)
		}
	}
}

:set newips
:set duration ([/system clock get time] - $duration)

/system logging enable 0
:log info "blocklist-REP: finished - enabled info"
:log info "blocklist-REP: finished - $countremoved removed, $countnew new, in $duration / $counttotal  total"
```

And then I have them scheduled via two Scheduler entries, every 3h, with 5min offset in start time, same policy for each respective schedule corresponding to the scripts.

Also running on 7.15.3.

**Comment by multiduplikator** [comment]
Oh, and you could delete the

`/system logging disable 0`

and

`/system logging enable 0`

from the script and observe the log for activity...

**Comment by TomHGitHub** [comment]
_l list works but takes forever. _xl crashes the console. This is probably a memory problem. I am currently working on an external bash script to prepare a firewall update script and ssh into the Mikrotik.
Thank you for your efforts. Tom.
